# Generated by Django 3.1.1 on 2020-09-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions_json', models.TextField(blank=True, null=True)),
                ('permissions_json_formatted', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('taxonomy_json', models.TextField(blank=True, null=True)),
                ('global_permission', models.CharField(blank=True, default='public', max_length=100, null=True)),
                ('inherit_permission', models.CharField(blank=True, max_length=100, null=True)),
                ('permissions_json', models.TextField(blank=True, null=True)),
                ('permissions_json_formatted', models.TextField(blank=True, null=True)),
                ('permission_inherit_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='test_page.testpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
