# Generated by Django 2.2.6 on 2020-07-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpage',
            name='permissions_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
