# Generated by Django 2.2.14 on 2020-08-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_page', '0002_testpage_permissions_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpage',
            name='global_permission',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testpage',
            name='inherit_permission',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
