# Generated by Django 3.1.1 on 2020-09-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_page', '0004_testpage_permission_inherit_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testpage',
            old_name='permission_inherit_page',
            new_name='parent_permission_page',
        ),
    ]
