# Generated by Django 2.2.4 on 2019-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_id', models.CharField(max_length=255, unique=True)),
                ('terms_json', models.TextField()),
            ],
        ),
    ]
